### PR TITLE
Update README.md

### LINKED ISSUE #3: Improve the data in README File

### PR DESCRIPTION
**Pull request by nitin094-hub**
fixes #3

### CODE REVIEW

**Comment by nitin094-hub** [comment]
Plz, don't merge it right now. I will make it much better.

**Comment by Programming-School-Pro-Coding** [comment]
> Plz, don't merge it right now. I will make it much better.

Ok

**Review by Programming-School-Pro-Coding — CHANGES_REQUESTED** [review]
Please add more informations

**Comment by Programming-School-Pro-Coding** [comment]
Hey @nitin094-hub

**Review by Programming-School-Pro-Coding — APPROVED** [review]
Amazing

**Pull request merged**
